# Generated by Django 4.0.3 on 2022-04-10 19:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import riding_sport_clubs.base_validators.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('owner', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2), riding_sport_clubs.base_validators.validators.owner_name_validator])),
                ('email_club', models.EmailField(max_length=254)),
                ('rating', models.IntegerField(default=0)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('club_logo', models.ImageField(blank=True, null=True, upload_to='clubs_logo')),
            ],
        ),
        migrations.CreateModel(
            name='HorseBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(choices=[('Friesian', 'Friesian'), ('Arabian', 'Arabian'), ('Andalusian', 'Andalusian')], max_length=35)),
                ('average_height', models.IntegerField()),
                ('horse_color', models.CharField(max_length=40)),
                ('common_uses', models.CharField(max_length=40)),
                ('breed_description', models.TextField(max_length=400000)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_first_name', models.CharField(max_length=25, validators=[riding_sport_clubs.base_validators.validators.name_validator])),
                ('trainer_last_name', models.CharField(max_length=25, validators=[riding_sport_clubs.base_validators.validators.name_validator])),
                ('trainer_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('trainer_phone_number', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(16), riding_sport_clubs.base_validators.validators.phone_number_validator])),
                ('trainer_photo', models.ImageField(blank=True, null=True, upload_to='trainer_photos')),
                ('trainer_info', models.TextField(blank=True, null=True)),
                ('clubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_clubs.club')),
            ],
        ),
    ]
