# Generated by Django 4.0.3 on 2022-04-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='award_bronze',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='award_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='award_silver',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='horsebreed',
            name='breed',
            field=models.CharField(choices=[('Arabian', 'Arabian'), ('Friesian', 'Friesian'), ('Andalusian', 'Andalusian')], max_length=35),
        ),
    ]
