# Generated by Django 4.0.3 on 2022-04-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_clubs', '0003_alter_club_options_alter_horsebreed_breed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={},
        ),
        migrations.AlterField(
            model_name='horsebreed',
            name='breed',
            field=models.CharField(choices=[('Andalusian', 'Andalusian'), ('Arabian', 'Arabian'), ('Friesian', 'Friesian')], max_length=35),
        ),
    ]
