# Generated by Django 4.0.3 on 2022-04-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_clubs', '0004_alter_club_options_alter_horsebreed_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='award_silver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horsebreed',
            name='breed',
            field=models.CharField(choices=[('Arabian', 'Arabian'), ('Andalusian', 'Andalusian'), ('Friesian', 'Friesian')], max_length=35),
        ),
    ]
