# Generated by Django 4.0.3 on 2022-04-23 13:20

import django.core.validators
from django.db import migrations, models
import riding_sport_clubs.base_validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web_clubs', '0006_alter_club_award_silver_alter_horsebreed_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horsebreed',
            name='breed',
            field=models.CharField(choices=[('Arabian', 'Arabian'), ('Friesian', 'Friesian'), ('Andalusian', 'Andalusian')], max_length=35),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(8), riding_sport_clubs.base_validators.validators.phone_number_validator]),
        ),
    ]
