# Generated by Django 4.0.3 on 2022-05-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_clubs', '0007_alter_horsebreed_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horsebreed',
            name='breed',
            field=models.CharField(choices=[('Friesian', 'Friesian'), ('Andalusian', 'Andalusian'), ('Arabian', 'Arabian')], max_length=35),
        ),
    ]
