# Generated by Django 4.0.3 on 2022-05-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_clubs', '0008_alter_horsebreed_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horsebreed',
            name='breed',
            field=models.CharField(choices=[('Andalusian', 'Andalusian'), ('Friesian', 'Friesian'), ('Arabian', 'Arabian')], max_length=35),
        ),
    ]
